// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zimat.Inventarios.Infrastructure.Data;

#nullable disable

namespace Zimat.Inventarios.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zimat.Inventarios.Core.ArticuloAggregate.Articulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("ClaveSat")
                        .HasColumnType("text")
                        .HasColumnName("clave_sat");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("text")
                        .HasColumnName("codigo_barras");

                    b.Property<decimal?>("CostoPromedio")
                        .HasColumnType("numeric")
                        .HasColumnName("costo_promedio");

                    b.Property<decimal?>("CostoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("costo_unitario");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("DescuentoMaximo")
                        .HasColumnType("numeric")
                        .HasColumnName("descuento_maximo");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_id");

                    b.Property<decimal>("Impuesto1")
                        .HasColumnType("numeric")
                        .HasColumnName("impuesto1");

                    b.Property<decimal>("Impuesto2")
                        .HasColumnType("numeric")
                        .HasColumnName("impuesto2");

                    b.Property<Guid?>("LineaId")
                        .HasColumnType("uuid")
                        .HasColumnName("linea_id");

                    b.Property<string>("Marca")
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("PesoNeto")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_neto");

                    b.Property<decimal>("PrecioPublico")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_publico");

                    b.Property<string>("RutaImagen")
                        .HasColumnType("text")
                        .HasColumnName("ruta_imagen");

                    b.Property<bool>("Series")
                        .HasColumnType("boolean")
                        .HasColumnName("series");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("numeric")
                        .HasColumnName("stock_actual");

                    b.Property<decimal>("StockMaximo")
                        .HasColumnType("numeric")
                        .HasColumnName("stock_maximo");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("numeric")
                        .HasColumnName("stock_minimo");

                    b.Property<int>("StockStatus")
                        .HasColumnType("integer")
                        .HasColumnName("stock_status");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text")
                        .HasColumnName("ubicacion");

                    b.Property<Guid?>("UltimaCompra")
                        .HasColumnType("uuid")
                        .HasColumnName("ultima_compra");

                    b.Property<Guid?>("UltimaVenta")
                        .HasColumnType("uuid")
                        .HasColumnName("ultima_venta");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_articulos");

                    b.HasIndex("UnidadId")
                        .HasDatabaseName("ix_articulos_unidad_id");

                    b.ToTable("articulos", (string)null);
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.ArticuloAggregate.ArticuloUnidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("FactorConversion")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("factor_conversion");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_articulo_unidades");

                    b.HasIndex("ArticuloId")
                        .HasDatabaseName("ix_articulo_unidades_articulo_id");

                    b.HasIndex("UnidadId")
                        .HasDatabaseName("ix_articulo_unidades_unidad_id");

                    b.ToTable("articulo_unidades", (string)null);
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.ArticuloAggregate.Precio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticuloUnidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_unidad_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("FactorCosto")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("factor_costo");

                    b.Property<decimal>("ImportePrecio")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("importe_precio");

                    b.Property<int>("NumeroLista")
                        .HasColumnType("integer")
                        .HasColumnName("numero_lista");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_precios");

                    b.HasIndex("ArticuloUnidadId")
                        .HasDatabaseName("ix_precios_articulo_unidad_id");

                    b.ToTable("precios", (string)null);
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.CategoriaAggregate.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Margen")
                        .HasColumnType("numeric")
                        .HasColumnName("margen");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.ClienteAggregate.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Calle")
                        .HasColumnType("text")
                        .HasColumnName("calle");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Colonia")
                        .HasColumnType("text")
                        .HasColumnName("colonia");

                    b.Property<string>("Contacto")
                        .HasColumnType("text")
                        .HasColumnName("contacto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DiasCredito")
                        .HasColumnType("integer")
                        .HasColumnName("dias_credito");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroExterior")
                        .HasColumnType("text")
                        .HasColumnName("numero_exterior");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("RegimenFiscal")
                        .HasColumnType("text")
                        .HasColumnName("regimen_fiscal");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rfc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.Property<string>("UsoCfdi")
                        .HasColumnType("text")
                        .HasColumnName("uso_cfdi");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.DepartamentoAggregate.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_departamentos");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.DocumentoAggregate.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AlmacenId")
                        .HasColumnType("integer")
                        .HasColumnName("almacen_id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric")
                        .HasColumnName("descuento");

                    b.Property<string>("Divisa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("divisa");

                    b.Property<Guid?>("DocumentoRelacionadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_relacionado_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("folio");

                    b.Property<int?>("FormaPagoId")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pago_id");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric")
                        .HasColumnName("importe");

                    b.Property<decimal>("Impuesto1")
                        .HasColumnType("numeric")
                        .HasColumnName("impuesto1");

                    b.Property<decimal>("Impuesto2")
                        .HasColumnType("numeric")
                        .HasColumnName("impuesto2");

                    b.Property<decimal>("PDescuento")
                        .HasColumnType("numeric")
                        .HasColumnName("p_descuento");

                    b.Property<bool>("Pagado")
                        .HasColumnType("boolean")
                        .HasColumnName("pagado");

                    b.Property<Guid?>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("Referencia")
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.Property<decimal>("SaldoAnticipo")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_anticipo");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TipoCambio")
                        .HasColumnType("numeric")
                        .HasColumnName("tipo_cambio");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_documento_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_documentos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_documentos_cliente_id");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_documentos_proveedor_id");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.DocumentoAggregate.DocumentoConcepto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric")
                        .HasColumnName("costo");

                    b.Property<decimal>("CostoPromedio")
                        .HasColumnType("numeric")
                        .HasColumnName("costo_promedio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric")
                        .HasColumnName("descuento");

                    b.Property<decimal>("Devueltos")
                        .HasColumnType("numeric")
                        .HasColumnName("devueltos");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric")
                        .HasColumnName("importe");

                    b.Property<decimal>("Impuesto1")
                        .HasColumnType("numeric")
                        .HasColumnName("impuesto1");

                    b.Property<decimal>("Impuesto2")
                        .HasColumnType("numeric")
                        .HasColumnName("impuesto2");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("text")
                        .HasColumnName("numero_serie");

                    b.Property<decimal>("Pendiente")
                        .HasColumnType("numeric")
                        .HasColumnName("pendiente");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric")
                        .HasColumnName("precio");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_documento_conceptos");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_documento_conceptos_documento_id");

                    b.ToTable("documento_conceptos", (string)null);
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.FamiliaAggregate.Familia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Margen")
                        .HasColumnType("numeric")
                        .HasColumnName("margen");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_familias");

                    b.ToTable("familias", (string)null);
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.LineaAggregate.Linea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Margen")
                        .HasColumnType("numeric")
                        .HasColumnName("margen");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_lineas");

                    b.ToTable("lineas", (string)null);
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.ProveedorAggregate.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Calle")
                        .HasColumnType("text")
                        .HasColumnName("calle");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<string>("Clasificacion")
                        .HasColumnType("text")
                        .HasColumnName("clasificacion");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Colonia")
                        .HasColumnType("text")
                        .HasColumnName("colonia");

                    b.Property<string>("Contacto")
                        .HasColumnType("text")
                        .HasColumnName("contacto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CuentaContable")
                        .HasColumnType("text")
                        .HasColumnName("cuenta_contable");

                    b.Property<int>("DiasCredito")
                        .HasColumnType("integer")
                        .HasColumnName("dias_credito");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroExterior")
                        .HasColumnType("text")
                        .HasColumnName("numero_exterior");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rfc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<int>("TipoProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_proveedor");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_proveedores");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.UnidadAggregate.Unidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClaveSat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave_sat");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_unidades");

                    b.ToTable("unidades", (string)null);
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.ArticuloAggregate.Articulo", b =>
                {
                    b.HasOne("Zimat.Inventarios.Core.UnidadAggregate.Unidad", null)
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_articulos_unidades_unidad_id");
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.ArticuloAggregate.ArticuloUnidad", b =>
                {
                    b.HasOne("Zimat.Inventarios.Core.ArticuloAggregate.Articulo", null)
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_articulo_unidades_articulos_articulo_id");

                    b.HasOne("Zimat.Inventarios.Core.UnidadAggregate.Unidad", null)
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_articulo_unidades_unidades_unidad_id");
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.ArticuloAggregate.Precio", b =>
                {
                    b.HasOne("Zimat.Inventarios.Core.ArticuloAggregate.ArticuloUnidad", null)
                        .WithMany("Conceptos")
                        .HasForeignKey("ArticuloUnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_precios_articulo_unidades_articulo_unidad_id");
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.DocumentoAggregate.Documento", b =>
                {
                    b.HasOne("Zimat.Inventarios.Core.ClienteAggregate.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_documentos_clientes_cliente_id");

                    b.HasOne("Zimat.Inventarios.Core.ProveedorAggregate.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_documentos_proveedores_proveedor_id");
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.DocumentoAggregate.DocumentoConcepto", b =>
                {
                    b.HasOne("Zimat.Inventarios.Core.DocumentoAggregate.Documento", null)
                        .WithMany("Conceptos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documento_conceptos_documentos_documento_id");
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.ArticuloAggregate.ArticuloUnidad", b =>
                {
                    b.Navigation("Conceptos");
                });

            modelBuilder.Entity("Zimat.Inventarios.Core.DocumentoAggregate.Documento", b =>
                {
                    b.Navigation("Conceptos");
                });
#pragma warning restore 612, 618
        }
    }
}
